# Generated by Django 5.0.1 on 2024-02-05 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='menu_items_description',
            new_name='description',
        ),
    ]
