# Generated by Django 5.0.2 on 2024-02-21 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_description_menu_menu_item_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='menu_item_description',
            new_name='description',
        ),
    ]
